{{- /*
 Get all the namespaces that we require from the list of applications. 
 By using a 'dict' we ensure that we get a unique list
*/ -}}

{{- $namespaces := dict -}}

{{- range .Values.applications }}
{{- $app := . }}
{{- range .namespace }}
{{- $_ := set $namespaces . . -}}
{{- end }}
{{- end }}

{{- range $namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
---
{{- end }}